### ISSUE TITLE
Transparent background on Ubuntu 16.10

### ISSUE THREAD

**Issue by menesis** [gtimelog/gtimelog#96] opened 2016-11-07 15:09 UTC
On Ubuntu 16.10 and running from source, main widget background is transparent, with gradients on edges.

![image](https://cloud.githubusercontent.com/assets/265668/20062336/07e83e4c-a50c-11e6-8383-f65fd4c5ee8d.png)

With default theme (Ambiance).
With Adwaita theme looks good.

GTK+ 3.20.9

There was a similar bug last year #62

**Comment by mgedmin** [comment] 2016-11-08 07:44
I cannot reproduce under GNOME Shell on Ubuntu 16.10 (also GTK+ 3.20.9):

```
$ sudo apt install light-themes
$ GTK_THEME=Ambiance gtimelog
```

![ekrano nuotrauka is 2016-11-08 09-42-27](https://cloud.githubusercontent.com/assets/159967/20090771/d80e829e-a597-11e6-9042-eb3ac57940ce.png)

**Comment by mgedmin** [comment] 2016-11-08 07:45
@menesis could you experiment by replacing the conditional in https://github.com/gtimelog/gtimelog/blob/master/src/gtimelog/main.py#L557

```python
        if (Gtk.MAJOR_VERSION, Gtk.MINOR_VERSION) < (3, 14):
            main_stack.connect('draw', self.draw_main_stack)
```

with `if True`?

**Comment by menesis** [comment] 2016-11-08 15:20
Tried it. Nothing changed.

If I change `src/gtimelog/gtimelog.css` `background-color` to `red`, it has no effect. Replace `GtkStack` with `stack` – only the bottom box background becomes red.

**Comment by mgedmin** [comment] 2016-11-08 17:22
Well, it was too much to hope that old fixes would help with new bugs :(

**Comment by bil-elmoussaoui** [comment] 2017-01-10 06:55
@mgedmin I think you should use `@theme_bg_color` instead of `@bg_color`. Also to avoid using stack or GtkStack just add CSS class name using `main_stack.get_style_context().add_class(".stack")` and replace 
`stack` to `.stack` in the CSS file

**Comment by mgedmin** [comment] 2017-01-10 08:37
I wish I could at least reproduce this bug...

**Comment by mgedmin** [comment] 2018-03-05 15:35
Can anyone reproduce this on Ubuntu 17.10?

**Comment by mgedmin** [comment] 2018-11-02 16:21
I'm going to close this, as Ubuntu 16.10 is long out of security support, and I haven't been able to reproduce this in any newer Ubuntu version.

**Closed by mgedmin** 2018-11-02 16:21 UTC
Labels: help wanted, question
