### ISSUE TITLE
Report for 'last month' on 1 April generated report for Feb instead of March

### ISSUE THREAD

**Issue by rapmankin** [gtimelog/gtimelog#87] opened 2016-04-01 09:06 UTC
Running v0.9.1 Ubuntu 14.04

At 10:00 (UTC+1) on 1 April I asked for a report for 'last month' and got February instead of March. The report for 'this month' gave me March.

BTW I realise that today is April Fool's day.

**Comment by mgedmin** [comment] 2016-04-01 12:12
I was unable to reproduce this using gtimelog 0.9.3.  Can you answer the following questions to help me narrow it down?

- Did you start GTimeLog today, or was it left running since yesterday?

- Have you entered any tasks today before attempting to generate reports?

**Comment by rapmankin** [comment] 2016-04-01 17:19
On Fri, 2016-04-01 at 05:12 -0700, Marius Gedminas wrote:
> I was unable to reproduce this using gtimelog 0.9.3. Can you answer
> the following questions to help me narrow it down?
> 
>       * Did you start GTimeLog today, or was it left running since
>         yesterday?

Generally it is running all the time. I did restart it either today or
yesterday. IIRC I restarted yesterday.
>         
>       * Have you entered any tasks today before attempting to generate
>         reports?

No.

**Comment by mgedmin** [comment] 2016-04-01 18:33
Ah, then I think I know what the bug is: gtimelog used to not notice that a new day has dawned until you started entering new data.

I don't remember if I fixed it in the 0.9.3/0.10.0 releases.  I'm quite sure the bug is gone in the current master.  I'll keep this issue open until there's a release that I definitely know doesn't have this bug.

**Comment by mgedmin** [comment] 2018-03-05 15:37
This should be fixed in 0.11.

**Closed by mgedmin** 2018-03-05 15:37 UTC
Labels: bug
