### ISSUE TITLE
Exceptions with GTK 3.22 (on OpenSUSE Tumbleweed)

### ISSUE THREAD

**Issue by cipriancraciun** [gtimelog/gtimelog#122] opened 2018-08-03 07:38 UTC
I'm trying to run it on the latest OpenSUSE Tumbleweed and I get the following error:
````
  File "/tmp/gtimelog/src/gtimelog/main.py", line 1388, in set_up_completion
    self.completion_choices = Gtk.ListStore(str)
TypeError: GObject.__init__() takes exactly 0 arguments (1 given)
````

My package versions are as follows:
````
libglib-2_0-0            2.56.1-2.2
libgobject-2_0-0         2.56.1-2.2
libgtk-3-0               3.22.30-3.1
python2-cairo            1.15.1-1.2
python2-gobject          3.28.3-1.2
typelib-1_0-Gtk-3_0      3.22.30-4.1
typelib-1_0-Soup-2_4     2.62.2-2.1
````

I've tried both `master`, `0.11.1`, `0.11` with the same error.  (Tags `0.10.*` give other errors.)

**Comment by mgedmin** [comment] 2018-08-03 11:46
Thank you for the heads up!

Could you please check out a copy of [PyGObject](https://github.com/GNOME/pygobject) and run python [`examples/demo/demos/Entry/entry_completion.py`]()https://github.com/GNOME/pygobject/blob/master/examples/demo/demos/Entry/entry_completion.py to see if it works?  It uses the same

    store = Gtk.ListStore(str)

construction I do in gtimelog, and it works on my machine.

(I'm trying to narrow down whether this is a bug in Tumbleweed's pygobject, or if I'm doing something wrong in gtimelog somehow.)

**Comment by mgedmin** [comment] 2018-08-03 11:47
Oh, also, if you could cobble up some instructions how I could reproduce this in Docker, that would be very helpful (I'm unfamiliar with OpenSuSE and its package manager).

**Comment by mgedmin** [comment] 2018-08-03 11:51
(For the record, I'm on Ubuntu 18.04, with the same GTK+ 3.22.30, but with an older PyGObject 3.27.1.  Also I've disabled the GTK entry completion with `gsettings set org.gtimelog gtk-completion false` because it annoys me, but I can enable it right back and it works for me.)

**Comment by cipriancraciun** [comment] 2018-08-03 11:54
Running the following:
````
python2 entry_completion.py
````

I get:
````
./entry_completion.py:29: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
Segmentation fault (core dumped)
````

Adding the following just before the first import still segfaults:
````
import gi
gi.require_version('Gtk', '3.0')
````

**Comment by cipriancraciun** [comment] 2018-08-03 11:59
BTW, I am not using a Gnome (or KDE) based desktop, instead I use `i3-wm`, thus maybe something isn't initialized?

Regarding the docker image, all you need to do is start a fresh OpenSUSE Tumbleweed container, and run the following:
````
zypper install python2 python2-cairo python2-gobject typelib-1_0-Gtk-3_0 typelib-1_0-Soup-2_4
````

**Comment by mgedmin** [comment] 2018-08-03 12:58
So it looks like pygobject in OpenSuSE is currently broken.  Can you report it in the appropriate bug tracker?

**Comment by cipriancraciun** [comment] 2018-08-03 13:40
I've submitted it at:

  https://bugzilla.opensuse.org/show_bug.cgi?id=1103735

**Comment by mgedmin** [comment] 2018-11-02 16:19
I'm going to close this here because I don't think I can do anything in gtimelog to protect against a segfault in pygobject.

**Closed by mgedmin** 2018-11-02 16:19 UTC
Labels: invalid
